name: E2E WEBHOOK Tests

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  e2e_webhook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-project

    - uses: mansagroup/nrwl-nx-action@v3
      with:
        targets: lint
        projects: '@novu/webhook'

    - name: Start Local Stack
      env:
        AWS_DEFAULT_REGION: us-east-1
        DEFAULT_REGION: us-east-1
        AWS_ACCOUNT_ID: '000000000000'
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_EC2_METADATA_DISABLED: true
      working-directory: docker/local
      run: |
        docker-compose -f docker-compose.localstack.yml up -d
        sleep 10
        max_retry=30
        counter=0
        until $command
        do
          sleep 1
          [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
          aws --endpoint-url=http://localhost:4566 s3 ls
          echo "Trying again. Try #$counter"
          ((counter++))
        done
        docker-compose -f docker-compose.localstack.yml logs --tail="all"
        aws --endpoint-url=http://localhost:4566 --cli-connect-timeout 600 s3 mb s3://novu-test

      # Runs a single command using the runners shell
    - name: Build API
      run: CI='' pnpm build:webhook

    # Runs a set of commands using the runners shell
    - name: Run a test
      run: | 
        cd apps/webhook && pnpm test:e2e
        pnpm test
