name: Test @novu/node
on:
  push:
    paths:
      - "packages/node/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          projects: "@novu/node"
          nxCloud: true

      - name: Test
        working-directory: "packages/node"
        run: pnpm test
