name: Test @novu/notification-center-angular
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/notification-center-angular/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build,test
          projects: '@novu/notification-center-angular'
          nxCloud: true
