# This is a basic workflow to help you get started with Actions

name: Test EMBED

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:
    paths:
      - 'libs/embed/**'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_embed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project

      # Runs a single command using the runners shell
      - name: Build
        run: pnpm build:embed
