name: Test docs
on:
  pull_request:
    paths:
      - "docs/**"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-project

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          projects: "@novu/docs"
          nxCloud: true
